FROM python:3.11-slim

RUN pip install --no-cache-dir dbt-bigquery==1.9.0

WORKDIR /dbt

COPY models/    models/
COPY macros/    macros/
COPY dbt_project.yml .
COPY profiles.yml    .
COPY run_dbt.sh      /run_dbt.sh

RUN chmod +x /run_dbt.sh

ENTRYPOINT ["/run_dbt.sh"]
